apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"spring-starter-5b4895888","uid":"29f6c9ec-cad1-11e7-946d-0800273d8376","apiVersion":"extensions","resourceVersion":"35308"}}
  creationTimestamp: 2017-11-16T13:22:15Z
  generateName: spring-starter-5b4895888-
  labels:
    pod-template-hash: "160451444"
    run: spring-starter
  name: spring-starter-5b4895888-fgvgw
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: spring-starter-5b4895888
    uid: 29f6c9ec-cad1-11e7-946d-0800273d8376
  resourceVersion: "35325"
  selfLink: /api/v1/namespaces/default/pods/spring-starter-5b4895888-fgvgw
  uid: 29f88532-cad1-11e7-946d-0800273d8376
spec:
  containers:
  - image: spring-starter:v1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: 7001
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 120
      successThreshold: 1
      timeoutSeconds: 5
    name: spring-starter
    ports:
    - containerPort: 7001
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ckjj8
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: minikube
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-ckjj8
    secret:
      defaultMode: 420
      secretName: default-token-ckjj8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-11-16T13:22:15Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-11-16T13:22:16Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-11-16T13:22:15Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9dd299e40c65442a8ee9f85fa9457253926b23e2ac08d61498990e18fb8adf52
    image: spring-starter:v1
    imageID: docker://sha256:e6a5d4f837f2a6af882ba12de106a94c8a112870b575133f6f64c3a9d61eae9c
    lastState: {}
    name: spring-starter
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2017-11-16T13:22:16Z
  hostIP: 192.168.99.100
  phase: Running
  podIP: 172.17.0.4
  qosClass: BestEffort
  startTime: 2017-11-16T13:22:15Z
