apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-11-16T13:22:15Z
  generation: 1
  labels:
    run: spring-starter
  name: spring-starter
  namespace: default
  resourceVersion: "35327"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/spring-starter
  uid: 29f648ae-cad1-11e7-946d-0800273d8376
spec:
  replicas: 1
  selector:
    matchLabels:
      run: spring-starter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: spring-starter
    spec:
      containers:
      - image: spring-starter:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 7001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 5
        name: spring-starter
        ports:
        - containerPort: 7001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-11-16T13:22:15Z
    lastUpdateTime: 2017-11-16T13:22:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
